# 服务端口号
server:
  port: 8003
spring:
  application:
    name: gateway # 对外暴露的服务名称
  cloud:
    gateway:
      routes:
        - id: before_route
          uri: http://www.baidu.com
          predicates:
            - Path=/baidu