# 服务端口号
server:
  port: 8002
spring:
  application:
    name: consumer # 对外暴露的服务名称
  cloud:
    nacos:
      discovery:
        server-addr: 118.25.67.106:8848
    alibaba:
      seata:
        tx-service-group: SEATA_GROUP
  datasource:
    url: jdbc:mysql://118.25.67.106:3306/test
    username: root
    password: yuanyun520.
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver